### PR TITLE
fix(mcp): fix mcp codegen, pin MCP SDK to v1.3.0, and sync workspace

### LINKED ISSUE #11: Generated MCP builds fail due to go.work/toolchain version mismatch
## Summary
The generated `mcp` marketing-agency build fails during Docker image build because the generated Go workspace and Docker toolchain versions are inconsistent.

## Repro
From `examples/marketing-agency/wiring`:

```bash
go run main.go -w mcp -o /tmp/marketing-agency-mcp -modfile=./example_model.json
cd /tmp/marketing-agency-mcp/docker
docker compose up -d --build
```

## Failure
The generated MCP containers fail during `go mod download` with errors like:

```text
go: module website_proc listed in go.work file requires go >= 1.25.0, but go.work lists go 1.23.1; to update it:
	go work use
```

I reproduced this in the generated marketing-agency MCP stack. The same mismatch showed up across the generated MCP processes.

## Root cause
The generated MCP artifacts are internally inconsistent:

- generated module `go.mod` files require `go 1.25.0`
- generated `go.work` files use `go 1.23.1`
- generated MCP Dockerfiles build with `FROM golang:1.23-bookworm`

That combination causes `go mod download` to fail inside the generated Docker build.

## Exact workaround used
I was able to get the generated MCP stack running only by patching the generated artifacts after codegen:

1. Update each generated MCP Dockerfile from:

```Dockerfile
FROM golang:1.23-bookworm AS ...
```

to:

```Dockerfile
FROM golang:1.25-bookworm AS ...
```

2. Update each generated MCP `go.work` file from:

```text
go 1.23.1
```

to:

```text
go 1.25.0
```

In my run, this had to be applied to these generated files:

- `docker/coordinator_ctr/Dockerfile`
- `docker/domain_ctr/Dockerfile`
- `docker/logo_ctr/Dockerfile`
- `docker/marketing_ctr/Dockerfile`
- `docker/website_ctr/Dockerfile`
- `docker/coordinator_ctr/coordinator_proc/go.work`
- `docker/domain_ctr/domain_proc/go.work`
- `docker/logo_ctr/logo_proc/go.work`
- `docker/marketing_ctr/marketing_proc/go.work`
- `docker/website_ctr/website_proc/go.work`

## Expected behavior
The generated `mcp` build should work without manual post-generation patching.

## Notes
- I observed this specifically with the `examples/marketing-agency/wiring` MCP spec.
- `single` and `http` worked without needing this workaround.
- After the generated-artifact patch above, the MCP stack built and responded successfully.

### PR DESCRIPTION
**Pull request by Abdomash**
closes #11 

This PR contains three cleanup items for the MCP plugin:

### 1. Pin MCP Go SDK to `v1.3.0`

I pinned `github.com/modelcontextprotocol/go-sdk` on version **v1.3.0** in both `clientgen.go` and `servergen.go`. This version requires Go 1.23+, which works with Blueprint's generated Dockerfile images directly, avoiding any patch scripts.

In the future, we can bump the mcp sdk to a higher version (or latest) once blueprint support it.

### 2. Fix name conflict in MCP server codegen

Once I fixed the MCP compilation, the `weather` example started working again, but the `marketing-agency` example was still broken. It turned out that the generated `MCPServer.go` template used `ctx` and `req` as parameter names, but they are also used in the `marketing-agency` example. These params collided when I ran `docker compose build`, so I renamed them to `mcpCtx` and `mcpReq` and that worked.

Error message I got:
```
------
 > [coordinator_ctr coordinator_proc 6/6] RUN go build -o /coordinator_proc ./coordinator_proc:
60.99 # blueprint/goproc/coordinator_proc/mcp
60.99 coordinator_proc/mcp/MarketingCoordinator_MCPServer.go:56:6: no new variables on left side of :=
60.99 coordinator_proc/mcp/MarketingCoordinator_MCPServer.go:56:9: cannot use params.Req (variable of type workflow.CampaignRequest) as *"github.com/modelcontextprotocol/go-sdk/mcp".CallToolRequest value in assignment
60.99 coordinator_proc/mcp/MarketingCoordinator_MCPServer.go:58:51: cannot use req (variable of type *"github.com/modelcontextprotocol/go-sdk/mcp".CallToolRequest) as workflow.CampaignRequest value in argument to handler.Service.CreateCampaign
------
Dockerfile:27
--------------------
```

> I didn't include the `mcp` wiring for the marketing-agency example here, it will be in another PR.

### 3. Run `go work sync`

ran `go work sync` across the repo so that all deps are updated. This bumps project's go version to 1.23.

> Once this PR gets merged, I will rebase #12 on it to remove the version update stuff from #12.

### CODE REVIEW

File: ai_plugins/mcp/mcpcodegen/servergen.go [hunk 1]
```diff
@@ -86,11 +88,11 @@ type {{$f.Name}}Params struct {
 	{{end}}
 }
 
-func (handler *{{$receiver}}) {{$f.Name -}} (ctx context.Context, req *mcp.CallToolRequest, params *{{$f.Name}}Params) (*mcp.CallToolResult, any, error) {
+func (handler *{{$receiver}}) {{$f.Name -}} (mcpCtx context.Context, mcpReq *mcp.CallToolRequest, params *{{$f.Name}}Params) (*mcp.CallToolResult, any, error) {
```
Comment (vaastav) [inline ai_plugins/mcp/mcpcodegen/servergen.go]: I think you only needed to change req here. You can leave ctx variable as is (ctx variable as a parameter is never parsed by the blueprint compiler)

**Review by vaastav — APPROVED** [review]
Just change the mcpCtx back to ctx and then we can merge this.

**Comment by Abdomash** [comment]
> Just change the mcpCtx back to ctx and then we can merge this.

Done.

File: ai_plugins/mcp/mcpcodegen/servergen.go (hunk 1 above)
Comment (Abdomash) [reply ai_plugins/mcp/mcpcodegen/servergen.go]: Got it.
